function [g] = darcy_metric(jac,invg,perm)

detK = perm.kxx .* (perm.kyy .* perm.kzz - perm.kyz.^2) ...
     - perm.kxy .* (perm.kxy .* perm.kzz - perm.kyz.* perm.kxz) ...
     + perm.kxz .* (perm.kxy .* perm.kyz - perm.kyy .* perm.kxz);

invK = 1 ./ detK;

perm.k11 = (perm.kyy .* perm.kzz - perm.kyz.^2);
perm.k12 = -(perm.kxy .* perm.kzz - perm.kyz.* perm.kxz);
perm.k13 = (perm.kxy .* perm.kyz - perm.kyy .* perm.kxz);
perm.k22 = (perm.kxx .* perm.kzz - perm.kyz .* perm.kxz);
perm.k23 = -(perm.kxx .* perm.kyz - perm.kxy .* perm.kxz);
perm.k33 = (perm.kxx .* perm.kyy - perm.kxy .^2);

g.g11 = (perm.k11 .* jac.dXdxii .^2 + perm.k22 .* jac.dYdxii .^2 + perm.k33 .* jac.dZdxii .^2 ...
    + 2 * perm.k12 .* jac.dXdxii .* jac.dYdxii + 2 * perm.k13 .* jac.dXdxii .* jac.dZdxii + 2 * perm.k23 .* jac.dYdxii .* jac.dZdxii) .* invg .* invK;

g.g22 = (perm.k11 .* jac.dXdeta .^2 + perm.k22 .* jac.dYdeta .^2 + perm.k33 .* jac.dZdeta .^2 ...
    + 2 * perm.k12 .* jac.dXdeta .* jac.dYdeta + 2 * perm.k13 .* jac.dXdeta .* jac.dZdeta + 2 * perm.k23 .* jac.dYdeta .* jac.dZdeta) .* invg .* invK;

g.g33 = (perm.k11 .* jac.dXdzta .^2 + perm.k22 .* jac.dYdzta .^2 + perm.k33 .* jac.dZdzta .^2 ...
    + 2 * perm.k12 .* jac.dXdzta .* jac.dYdzta + 2 * perm.k13 .* jac.dXdzta .* jac.dZdzta + 2 * perm.k23 .* jac.dYdzta .* jac.dZdzta) .* invg .* invK;

g.g12 = (perm.k11 .* jac.dXdxii .* jac.dXdeta + perm.k22 .* jac.dYdxii .* jac.dYdeta + perm.k33 .* jac.dZdxii .* jac.dZdeta ...
    + perm.k12 .* (jac.dXdxii .* jac.dYdeta + jac.dXdeta .* jac.dYdxii) ...
    + perm.k13 .* (jac.dXdxii .* jac.dZdeta + jac.dXdeta .* jac.dZdxii) ...
    + perm.k23 .* (jac.dYdxii .* jac.dZdeta + jac.dYdeta .* jac.dZdxii)) .* invg .* invK;

g.g13 = (perm.k11 .* jac.dXdxii .* jac.dXdzta + perm.k22 .* jac.dYdxii .* jac.dYdzta + perm.k33 .* jac.dZdxii .* jac.dZdzta ...
    + perm.k12 .* (jac.dXdxii .* jac.dYdzta + jac.dXdzta .* jac.dYdxii) ...
    + perm.k13 .* (jac.dXdxii .* jac.dZdzta + jac.dXdzta .* jac.dZdxii) ...
    + perm.k23 .* (jac.dYdxii .* jac.dZdzta + jac.dYdzta .* jac.dZdxii)) .* invg .* invK;

g.g23 = (perm.k11 .* jac.dXdeta .* jac.dXdzta + perm.k22 .* jac.dYdeta .* jac.dYdzta + perm.k33 .* jac.dZdeta .* jac.dZdzta ...
    + perm.k12 .* (jac.dXdeta .* jac.dYdzta + jac.dXdzta .* jac.dYdeta) ...
    + perm.k13 .* (jac.dXdeta .* jac.dZdzta + jac.dXdzta .* jac.dZdeta) ...
    + perm.k23 .* (jac.dYdeta .* jac.dZdzta + jac.dYdzta .* jac.dZdeta)) .* invg .* invK;

g.invg = invg;

end

